__author__ = ["Mirosław Kicia (mkicia@camk.edu.pl)"]
__copyright__ = ""
__credits__ = ["Mirosław Kicia (mkicia@camk.edu.pl)"]
__license__ = "MIT"
__version_num__ = [1, 1, 12] # Change also in pyproject.toml
__version__ = "{}.{}.{}".format(*__version_num__)
__maintainer__ = "Mirosław Kicia (mkicia@camk.edu.pl)"
__email__ = "mkicia@camk.edu.pl"
__status__ = "Development"
